<?php
/*
Plugin Name: Event Schema EM
Description: Add Event Schema to event pages generated by Events Manager WP Plugin to increase discoverability 
Author: Casey Conlin
*/
// Include eschemaem-functions.php, use require_once to stop the script if eschemaem-functions.php is not found
require_once plugin_dir_path(__FILE__) . 'includes/eschemaem-functions.php';
add_action( 'wp_head', 'e_schema_em1', 10);